import type { ApplicabilityResult, QcoItem } from "./api";

/**
 * Client-side export helpers. Everything here reformats data that is already
 * sourced and cited — no new facts are introduced.
 */

export function complianceNote(description: string, refNo: string, result: ApplicabilityResult): string {
  const lines: string[] = [];
  lines.push("COMPLIANCE NOTE (generated by BIS Sahayak)");
  lines.push(`Reference: ${refNo} (generated receipt reference, not a BIS number)`);
  lines.push(`Date: ${new Date().toLocaleDateString("en-IN")}`);
  lines.push(`Product described as: ${description.trim()}`);
  lines.push("");
  lines.push(
    `Finding: ${result.mandatory ? "MANDATORY" : "NOT MANDATORY (per seeded corpus)"} BIS certification — scheme: ${
      result.scheme ?? "not specified"
    }`,
  );
  lines.push("");
  lines.push("Applicable Indian Standards:");
  for (const s of result.standards) {
    lines.push(`  - ${s.is_number}: ${s.title}${s.source_url ? ` (source: ${s.source_url})` : ""}`);
  }
  if (result.qcoRefs.length > 0) {
    lines.push("");
    lines.push("Covering Quality Control Orders:");
    for (const q of result.qcoRefs) {
      lines.push(
        `  - ${q.ref} (effective ${q.effective_date ?? "see source"}; standards: ${q.standards.join(", ")})${
          q.source_url ? ` (source: ${q.source_url})` : ""
        }`,
      );
    }
  }
  lines.push("");
  lines.push(
    "Note: machine-assisted finding verified against BIS Sahayak's seeded corpus of public BIS metadata. Not a legal opinion; verify against the Gazette.",
  );
  return lines.join("\n");
}

function icsEscape(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\n/g, "\\n");
}

function icsDate(iso: string): string {
  return iso.replace(/-/g, "");
}

/** Build an ICS calendar of upcoming QCO effective dates (only future-dated ones). */
export function icsForQcos(items: QcoItem[]): string {
  const now = new Date();
  const stamp = `${now.getUTCFullYear()}${String(now.getUTCMonth() + 1).padStart(2, "0")}${String(
    now.getUTCDate(),
  ).padStart(2, "0")}T000000Z`;
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//BIS Sahayak//QCO Radar//EN",
    "CALSCALE:GREGORIAN",
  ];
  for (const item of items) {
    if (!item.effective_date || item.effective_date < new Date().toISOString().slice(0, 10)) continue;
    lines.push(
      "BEGIN:VEVENT",
      `UID:qco-${item.id}@bis-sahayak`,
      `DTSTAMP:${stamp}`,
      `DTSTART;VALUE=DATE:${icsDate(item.effective_date)}`,
      `SUMMARY:${icsEscape(`QCO in force: ${item.title}`)}`,
      `DESCRIPTION:${icsEscape(
        `Scheme: ${item.scheme ?? "see source"}. Standards: ${item.applicable_is_numbers.join(", ") || "see source"}. ${item.summary} Source: ${item.source_url}`,
      ).slice(0, 900)}`,
      "BEGIN:VALARM",
      "TRIGGER:-P30D",
      "ACTION:DISPLAY",
      `DESCRIPTION:${icsEscape(`QCO effective in 30 days: ${item.title}`)}`,
      "END:VALARM",
      "END:VEVENT",
    );
  }
  lines.push("END:VCALENDAR");
  return lines.join("\r\n");
}

export function downloadText(filename: string, text: string, mime = "text/plain"): void {
  const blob = new Blob([text], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

export function haversineKm(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371;
  const toRad = (d: number) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 + Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return 2 * R * Math.asin(Math.sqrt(a));
}
